# Generated by Django 3.0.5 on 2020-04-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
