version: '2'

services:
  test:
    build:
      context: .
      dockerfile: ./workspace/Dockerfile
    user: root
    command: "/var/log/erss/workspace/per_request 2048" 
    volumes:
      - .:/var/log/erss
    ports:
      - "12345:12345"
    network_mode: host
    cpuset: 0,1,2,3
    tty: true